name: Scrape Bids Online PDF

on:
  workflow_dispatch: {}   # Allow manual trigger
  schedule:
    # Run at minute 30, every 8 hours (00:30, 08:30, 16:30 UTC)
    - cron: "30 */8 * * *"

permissions:
  contents: write   # Needed to push updated JSON

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java (for tabula-py)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          BIDSONLINE_URL: https://www.msfirm.com/bids/bidsonline.pdf
          OUT_PATH: bids.json
        run: |
          python scraper.py

      - name: Commit & push if changed
        run: |
          set -e
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add bids.json
            git commit -m "chore: update bids.json [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
